### ISSUE TITLE
console-setup no longer sets fontface or fontsize

### ISSUE THREAD

**Issue by klutchell** [klutchell/balena-pihole#145]
In recent releases by devices with screens are compressing the PADD output and only using the top half of the display.

Unclear at this point if it is related to FBCP, or the balenaOS release, or something else altogether.

**Comment by eiddor** [comment]
Hmmmm - I haven't seen this issue in a long time.  I believe the last time I saw it was when I realized that we had a font/font size option.

**Comment by klutchell** [comment]
What type of screen do you have, and what balenaOS version are you running? What is your value for `FBCP_DISPLAY` and other HDMI related device configuration?

**Comment by eiddor** [comment]
I've got the official RPi 7" (I think?) screen.  FBCP_DISPLAY is dtoverlay, and here are the rest of my settings.

![image](https://user-images.githubusercontent.com/7586731/166501684-f547a601-1888-483f-95c1-eac95575a945.png)
![image](https://user-images.githubusercontent.com/7586731/166501794-1d1826a2-3fec-415e-be20-e18c6cd2abf6.png)
![image](https://user-images.githubusercontent.com/7586731/166502394-5df27e45-2f31-4694-8eb7-be7a7d261130.png)

**Comment by klutchell** [comment]
I'm running a newer balenaOS release, I wonder if something changed in the upstream display firmware we need to take into account now.

**Comment by eiddor** [comment]
Let me upgrade and I'll let you know.

**Comment by eiddor** [comment]
Yep - Upgraded to the latest recommended balenaOS release and I've got the same issue.

**Comment by klutchell** [comment]
This appears to work with privileged mode, so we are missing either a capability or a device that is required for `console-setup` to actually take effect on `tty1`.

I am opening a PR to restore the ability to use privileged mode upstream. I also intend to figure out what we are missing for console-setup so we can continue to not run as privileged.
