### ISSUE TITLE
Automatic config management for pihole?

### ISSUE THREAD

**Issue by nmelin** [klutchell/balena-pihole#16]
@klutchell As far as I can tell, the only configuration management in balena-pihole is manual export/import via Teleporter.

I would like to automatically commit to private git repositories whenever the configuration is updated, such as when a new blocklist is added, or when whitelist and blacklist entries are updated.

Would the addition of a 3rd Balena service be a good strategy for configuration management?    The 3rd container could run [gitwatch](https://github.com/gitwatch/gitwatch) to monitor and commit any changes to the named volumes.  etckeeper is another option, though it might be overkill.

If a gitwatch service is implemented, should the pihole Dockerfile  be updated to pull `/etc/pihole` and `/etc/dnsmasq.d` from git during build?

**Comment by klutchell** [comment]
What you've described with a 3rd service sounds like it should work for the git commit and push using gitwatch. For the restore/pull I would personally add a new init file to the pihole container (similar to `30-checktft.sh`) that pulls the latest config from the remote before the pihole app starts.
