### ISSUE TITLE
Unable to locate package libraspberrypi-dev when running balena push myProject

### ISSUE THREAD

**Issue by briggleman** [klutchell/balena-pihole#30]
When running `balena push myProject` the following build error is returned.

```sh
[pihole]          Reading package lists...
[pihole]          Building dependency tree...
[pihole]          Reading state information...
[pihole]          E: Unable to locate package libraspberrypi-dev
```

**Comment by klutchell** [comment]
Unfortunately this project does not work on the 64-bit OS. Can you try again with the standard Raspberry Pi balenaOS image?

https://github.com/klutchell/balena-pihole/issues/29

**Comment by briggleman** [comment]
It hit me as soon as I entered this ticket.  Yes, I will try on a non 64-bit OS and re-open if issues persist.
