### ISSUE TITLE
Will not deploy to Raspberry Pi 4 applications

### ISSUE THREAD

**Issue by chrisys** [klutchell/balena-pihole#31]
https://github.com/klutchell/balena-pihole/commit/11b72da3048ebb88574f9dec539c3a6c3bfbc7fb#diff-74512d05221c38c6577f092551211163L1

Due to the above change, the project will no longer build for Raspberry Pi 4 devices running 64-bit OS as the `libraspberrypi-dev` package does not exist for `aarch64`. The quickest way to resolve this is to duplicate the `Dockerfile.template` as `Dockerfile.aarch64` and force the machine name back to `raspberrypi3` as it was before. I'll PR this for reference.

**Comment by chrisys** [comment]
Related thread: https://forums.balena.io/t/raspberrypi-4-pihole-libraspberrypi-dev-error/53003/6

**Comment by klutchell** [comment]
thanks!
