### ISSUE TITLE
The web service root path does not serve a working page

### ISSUE THREAD

**Issue by roman-mazur** [klutchell/balena-pihole#33]
People try to open their root device URL to see the PiHole dashboard, but get a non-working page instead without hints they should open `/admin` instead.
See this discussion for an example:
https://forums.balena.io/t/pihole-public-url-doesnt-appear-to-work/58030/18

It might be worth fixing the root page. It currently tries to load CSS/JS from a `pi.hole` domain, which does not work.

**Comment by klutchell** [comment]
Unfortunately we are not able to fix the root page, as that is part of Pi-Hole's core functionality.

This is mentioned on the [guide](https://www.balena.io/blog/deploy-network-wide-ad-blocking-with-pi-hole-and-a-raspberry-pi/) but maybe it would be helpful to have it identified on the README as well.
