### ISSUE TITLE
Can't get into dnscrypt-proxy container

### ISSUE THREAD

**Issue by drew-kun** [klutchell/balena-pihole#35]
When trying to get into the dnscrypt-proxy container getting:

```
$ balena ssh 192.168.2.2 dnscrypt-proxy
OCI runtime exec failed: exec failed: container_linux.go:345: starting container process caused "exec: \"/bin/sh\": stat /bin/sh: no such file or directory": unknown
Connection to 192.168.2.2 closed.
```

Similar results in BalenaCloud shell:
![Screen Shot 2020-02-09 at 8 42 00 PM](https://user-images.githubusercontent.com/10493450/74107835-b56bf300-4b7c-11ea-853d-98a8a60fd221.png)

Is it supposed to be possible to get there?

**Comment by klutchell** [comment]
That is by design. By not having a shell in the `scratch` base image we are lowering the possible attack surfaces of the container.

If you want to poke around in the dnscrypt-proxy container, try changing `FROM scratch` to `FROM alpine` in `dnscrypt-proxy/Dockerfile`.

**Comment by drew-kun** [comment]
Oh, I see! Thank you very much for explanation! Closing then..
