### ISSUE TITLE
Update to Pi-hole 5.0

### ISSUE THREAD

**Issue by mrseth** [klutchell/balena-pihole#41]
Is there a way to update to Pi-hole 5.0 using this container?

**Comment by klutchell** [comment]
Yes, but since it was only released yesterday on Docker I haven't had a chance to test it yet.

You can change `pihole/Dockerfile.armv7hf` (or `pihole/Dockerfile.aarch64` if your device is 64-bit) before pushing the project to your device.

```Dockerfile
# replace this line
FROM pihole/pihole:v4.4-armhf

# with this line
FROM pihole/pihole:v5.0-armhf
```

 I expect to have this project updated to v5.0 soon.

**Comment by mrseth** [comment]
Thanks so much!! Appreciate the quick response and great work you are doing!
