### ISSUE TITLE
Update to 5.0? 

### ISSUE THREAD

**Issue by t3pfaffe** [klutchell/balena-pihole#42]
As in the title. Is this setup safe to update to 5.0? Can I just change the [pihole/pihole:v4.4-armel](https://github.com/klutchell/balena-pihole/blob/master/pihole/Dockerfile.rpi) to 5.0? Or is their an incompatibility issue causing trouble with the newest version?

**Comment by klutchell** [comment]
It's safe to upgrade, I tested it on my devices and updated this project to v5.0 last week.

Thanks for checking out the project!

**Comment by t3pfaffe** [comment]
Oh, guess I didn't see that. Thanks!
