### ISSUE TITLE
Why the removal of Raspberry Pi 2?

### ISSUE THREAD

**Issue by tsialex** [klutchell/balena-pihole#61]
Why the reason for the removal of Raspberry Pi 2? I have balena-PiHole 5.4 running it on two Pi 2 and runs fine, even with the slightly older kernel of the balena host for it.
![Screen Shot 2021-01-20 at 14 52 11](https://user-images.githubusercontent.com/51399444/105214824-468a6e80-5b2f-11eb-9131-5427038fb9ac.png)

**Comment by klutchell** [comment]
@tsialex only because I don't have an Raspberry Pi 2 in order to test it!

If you can confirm that it works, which it seems you can, I'd be happy to add it back to `balena.yml` and on the README. Or you can open a PR for the change if you'd like it sooner?

**Comment by tsialex** [comment]
I can confirm that balena-pihole on the RPI2 works fine with the current 12.3.0 supervisor, no problems at all with two Pi2. I'll test a little more and then open the PR, thx.

**Comment by toastyghost710** [comment]
I can second that @tsialex my backup pihole installation is on a RPI2 and even with the most recent update to v5.5.1 there appears to be no issues.

<img width="829" alt="RPI2 Pi-Hole" src="https://user-images.githubusercontent.com/73500509/105223228-1fc53b80-5b21-11eb-995d-210ba224e010.png">
