### ISSUE TITLE
New Pihole Version 

### ISSUE THREAD

**Issue by clipse2004** [klutchell/balena-pihole#78]
Hi,
Me again ;) 
Quick question, there is an update available for Pihole. Is here the same procedure as for Unbound? So just load the ZIP file, adjust version and then push again?

Thank you

**Comment by klutchell** [comment]
Hey Marco, we have https://github.com/klutchell/balena-pihole/pull/77 already open for that change. We are just waiting to soak a little longer before we merge.

If you want to do it yourself, then just changing the version number is correct.

**Comment by clipse2004** [comment]
Sorry I overlooked that, otherwise I would have opened nix new :/
But thanks for the info ;)
