### ISSUE TITLE
Unable to resolve `pi.hole` in build `2021.10`

### ISSUE THREAD

**Issue by klutchell** [klutchell/balena-pihole#99]
This was working in build `2021.09` and appears to only impact Pi-hole instances in this balena fleet.

```bash
# 2021.09
> nslookup pi.hole 192.168.1.141           
Server:         192.168.1.141
Address:        192.168.1.141#53

Name:   pi.hole
Address: 192.168.1.141
Name:   pi.hole
Address: fe80::c88d:7302:fe39:bc60
```
```bash
# 2021.10
> nslookup pi.hole 192.168.1.141
Server:         192.168.1.141
Address:        192.168.1.141#53

Non-authoritative answer:
*** Can't find pi.hole: No answer
```

Investigation will be tracked here...

**Comment by klutchell** [comment]
Removing `bind-interfaces` from `/etc/dnsmasq.conf` and running in bridge networking seems to resolve the issue.

https://github.com/klutchell/balena-pihole/blob/8e2b989e20b5191fc3b64876edddbfb14a9d0d63/pihole/Dockerfile#L21

Disable this line ^^

```bash
nslookup pi.hole 192.168.1.141
Server:         192.168.1.141
Address:        192.168.1.141#53

Name:   pi.hole
Address: 192.168.1.141
```

Unfortunately bridge networking requires knowing the eth0 IP address and hardcoding it in docker-compose to avoid conflicts on port 53.

Investigation for alternative workarounds is ongoing...

**Comment by klutchell** [comment]
This will be fixed in the next FTL release: https://github.com/pi-hole/FTL/pull/1198

**Comment by eiddor** [comment]
I thought a quick workaround might be to add `$ServerIP pi.hole` to the end of `/etc/hosts` but that's also mentioned in the upstream issue as not working.
